[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./"}]
rpc_endpoints = {mumbai = "${MUMBAI_RPC_URL}", polygon = "${POLYGON_RPC_URL}"}
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = "0.8.19"
optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 2048
seed = "0xdeadbeef"